apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deploy
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-deploy
  template:
    metadata:
      labels:
        app: demo-app-deploy
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: demo-app-deploy
          image: ghcr.io/nithikorn-i/demo-app-deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "http://+:8080"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: dev
spec:
  selector:
    app: demo-app-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
