
services:
  service-worker-1:
    build:
      context: .
      dockerfile: Dockerfile-module-5
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/egat_web_api_module_5:${APP_VERSION}
    container_name: egat_web_api_module_5
    ports:
      - "8082:80" # Host:8082 -> Container:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      HTTP_PORTS: ""